# Generated by Django 2.2.3 on 2019-07-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_reservation',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='make_reservation',
            name='how_meny_person',
            field=models.CharField(max_length=20),
        ),
    ]
