# Generated by Django 2.2.3 on 2019-07-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appetizer', '0003_auto_20190718_0120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Happy_Customer',
            new_name='HappyCustomer',
        ),
    ]
