# Generated by Django 2.2.3 on 2019-07-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyChefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('name_jop', models.CharField(max_length=90)),
                ('bio', models.TextField()),
                ('social_media_twitter', models.URLField(default='#')),
                ('social_media_instagram', models.URLField(default='#')),
                ('social_media_facebook', models.URLField(default='#')),
                ('social_media_google', models.URLField(default='#')),
                ('img', models.ImageField(upload_to='about/chefs')),
            ],
        ),
    ]
