# Generated by Django 2.2.3 on 2019-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychefs',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='about/chefs'),
        ),
        migrations.AlterField(
            model_name='mychefs',
            name='social_media_facebook',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='mychefs',
            name='social_media_google',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='mychefs',
            name='social_media_instagram',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='mychefs',
            name='social_media_twitter',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
