# Generated by Django 2.2.3 on 2019-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bio', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='menu-img')),
                ('menu_details', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Desserts', 'Desserts'), ('Wine Card', 'Wine Card'), ('Drinks', 'Drinks')], max_length=200)),
            ],
        ),
    ]
